# Dockerfile.backend
FROM golang:1.24.6-alpine

WORKDIR /app

# Copiar módulos y descargar dependencias
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Copiar el resto del código
COPY backend/ .

# Compilar
RUN go build -o main ./cmd/main.go

EXPOSE 8080

CMD ["./main"]
